// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6df0d2ed-a9ae-452d-a4c9-2bf84edeaa47",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5VUcLiO6r",
    "aws_user_pools_web_client_id": "1aak33u9saujcolst1e2t1rd93",
    "oauth": {}
};


export default awsmobile;
